version: '3.8'

services:

  webadaptor:
    build: .
    image: arcgis/webadaptor:10.9.1
    restart: always
    hostname: agsipsdh.ddns.net
    container_name: WEBADAPTOR
    environment:
      -  HOST_IP_ADDRESS=103.52.213.191
    ports:
      -  "80:80"
      -  "443:443"
    networks:
      - webgis

networks:
  webgis:
    name: bck_webgis
    external: true
