volumes:
  postgis-data:

services:

  pgis:
    # build: .
    image: postgis/postgis:15-3.4   
    volumes:
      - postgis-data:/var/lib/postgresql/data
    environment:
      # If you need to create multiple database you can add coma separated databases eg gis,data
      - POSTGRES_DB=pgisdb
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - PGDATA=/var/lib/postgresql/data/pgdata
      - TZ=Asia/Jakarta
      - ALLOW_IP_RANGE=0.0.0.0/0
      # Add extensions you need to be enabled by default in the DB. Default are the five specified below
      # - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting
      # - RUN_AS_ROOT=true
    container_name: PGIS-15  
    ports:
      - "5432:5432"
    restart: on-failure
    healthcheck:
      test: "PGPASSWORD=docker pg_isready -h 127.0.0.1 -U docker -d pgisdb"

    networks:
      app_net:

networks:
   app_net:
     ipam:
       driver: default
       config:
         - subnet: 192.168.80.0/24
           gateway: 192.168.80.1
