FROM kartoza/postgis:12.4 

MAINTAINER Klik.On <abiyasa@gmail.com>
LABEL version="POSTGRESQL for ArcGIS-POSTGIS" \
          author="Klik.On" \
          description="This is for Klik.On"

COPY ./lib/* /usr/lib/postgresql/12/lib

