
services:
  gdal:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gdal-3114-postgis
    stdin_open: true
    tty: true
    volumes:
      - .:/data
    working_dir: /data
