services:

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "192.168.80.0/24"
        
  portal:
    build: portal-for-arcgis
    image: arcgis/portal:10.9.1
    volumes:
      - /mnt/test_share:/tmp/backup
    restart: always
    hostname: PORTAL.WEBGIS.LOKAL
    container_name: PORTAL
    ports:
      -  "7080:7080"
      -  "7443:7443"
    networks:
      -  webgis
    healthcheck:
      test: ["CMD", "/usr/bin/curl", "-Lkf", "https://localhost:7443/arcgis/home"]
      interval: 1m 
      timeout: 10s
      retries: 3
    networks:
      app_net:

  server:
    build: arcgis-server
    image: arcgis/server:10.9.1
    volumes:
      - /mnt/test_share:/tmp/backup
    restart: always
    hostname: SERVER.WEBGIS.LOKAL
    container_name: SERVER
    ports:
      -  "6080:6080"
      -  "6443:6443"
    networks:
      -  webgis
    healthcheck:
      test: ["CMD", "/usr/bin/curl", "-Lkf", "https://localhost:6443/arcgis/manager"]
      interval: 1m
      timeout: 10s
      retries: 3
    networks:
      app_net:
      
  datastore:
    build: datastore
    image: arcgis/datastore:10.9.1
    volumes:
      - /mnt/test_share:/tmp/backup
    restart: always
    hostname: DATASTORE.WEBGIS.LOKAL
    container_name: DATASTORE
    ports:
      -  "2443:2443"
      -  "9876:9876"
    networks:
      -  webgis
    depends_on:
      server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/usr/bin/curl", "-Lkf", "https://localhost:2443/arcgis/datastore"]
      interval: 1m
      timeout: 10s
      retries: 3
    networks:
      app_net:
      

