version: '3.8'

services:

  webadaptor:
    build: . 
    image: arcgis/webadaptor:10.9.1
    restart: always
    hostname: agsipsdh.menlhk.go.id    
    container_name: WEBADAPTOR
    environment:
      -  HOST_IP_ADDRESS=172.16.2.141
    ports:
      -  "80:80"
      -  "443:443"
    networks:
      -  webgis

networks:
  webgis:
    driver: bridge
