version: '3.8'

services:

  webadaptor:
    build: . 
    image: arcgis/webadaptor:10.9.1
    restart: always
    hostname: wbgis.ddns.net  
    container_name: WEBADAPTOR
    environment:
      -  HOST_IP_ADDRESS=192.168.1.100
    ports:
      -  "80:80"
      -  "443:443"
    networks:
      - webgis
    volumes:
      - webapps:/usr/local/tomcat/webapps

networks:
  webgis:
    name: docker-arcgis-enterprise_webgis
    external: true

volumes:
  webapps:
