FROM docker.io/bitnami/postgresql:12

MAINTAINER Klik.On <abiyasa@gmail.com>
LABEL version="POSTGRESQL for ArcGIS" \
          author="Klik.On" \
          description="This is for Klik.On"

COPY ./lib/* /opt/bitnami/postgresql/lib
