version: '2'

services:
  postgresql:
    build: .
    image: arcgis/pgsql:12.14.0
    # image: docker.io/bitnami/postgresql:12
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      
volumes:
  postgresql_data:
    driver: local
