version: '3'

services:
  postgresql:
    build: .
    image: arcgis/pgsql:12
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
    container_name: PGSQL-12

volumes:
  postgresql_data:
    driver: local
