version: '3'

services:
  postgresql:
    image: docker.io/bitnami/postgresql:12
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
    container_name: PGSQL-12
   
volumes:
  postgresql_data:
    driver: local
